export type Environment = {
  CONTENTFUL_API_BASE_URL: string;
  CONTENTFUL_DELIVERY_ACCESS_TOKEN: string;
  CONTENTFUL_ENVIRONMENT: string;
  CONTENTFUL_PREVIEW_ACCESS_TOKEN: string;
  CONTENTFUL_SPACEID: string;
};

export const CONTENTFUL_API_BASE_URL =
  process.env.EXPO_PUBLIC_CONTENTFUL_API_BASE_URL;
export const CONTENTFUL_DELIVERY_ACCESS_TOKEN =
  process.env.EXPO_PUBLIC_CONTENTFUL_DELIVERY_ACCESS_TOKEN;
export const CONTENTFUL_ENVIRONMENT =
  process.env.EXPO_PUBLIC_CONTENTFUL_ENVIRONMENT;
export const CONTENTFUL_PREVIEW_ACCESS_TOKEN =
  process.env.EXPO_PUBLIC_CONTENTFUL_PREVIEW_ACCESS_TOKEN;
export const CONTENTFUL_SPACEID = process.env.EXPO_PUBLIC_CONTENTFUL_SPACEID;
